apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i0nftasgc-python
  janus-idp.io/tekton: i0nftasgc-python
  backstage.io/kubernetes-id: i0nftasgc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i0nftasgc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
